#!/bin/bash
#SBATCH --account=lp_cmpa
#SBATCH --clusters=genius
#SBATCH --partition=gpu_p100
#SBATCH --job-name=ddp-torch     # create a short name for your job
#SBATCH --nodes=4               # node count 
#SBATCH --gres=gpu:2             # number of allocated gpus per node ### Note: --gres=gpu:x should equal to ntasks-per-node
#SBATCH --ntasks-per-node=2      # total number of tasks per node
#SBATCH --cpus-per-task=8        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem=32G                # total memory per node (4 GB per cpu-core is default)
#SBATCH --time=00:05:00          # total run time limit (HH:MM:SS)
#SBATCH --output=%x%j.out
#SBATCH --error=%x%j.err


### change 5-digit MASTER_PORT as you wish, slurm will raise Error if duplicated with others
### change WORLD_SIZE as gpus/node * num_nodes
export MASTER_PORT=12340 #$(get_free_port)
export WORLD_SIZE=$(($SLURM_NNODES * $SLURM_NTASKS_PER_NODE))
echo "WORLD_SIZE="$WORLD_SIZE
echo "MASTER_PORT="$MASTER_PORT

master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
echo "MASTER_ADDR="$MASTER_ADDR

#module purge
#module load anaconda3/2023.9
#conda activate torch-env
source ~/.bashrc
mamba activate huggingface_hub

srun python mnist_classify_ddp.py --epochs=2 --timing_name "time4nodes2gpu.csv"
